basePath: /
definitions:
  ds.Comics:
    properties:
      description:
        type: string
      genre:
        type: string
      image:
        type: string
      name:
        type: string
      price:
        type: integer
      rate:
        type: number
      uuid:
        type: string
      volumes:
        type: integer
      year:
        type: integer
    type: object
  models.ModelComicsCreated:
    properties:
      success:
        description: success
        type: boolean
    type: object
  models.ModelComicsDeleted:
    properties:
      delete:
        type: boolean
    type: object
  models.ModelComicsDesc:
    properties:
      description:
        type: string
    type: object
  models.ModelDescChanged:
    properties:
      description:
        type: boolean
    type: object
  models.ModelError:
    properties:
      description:
        description: description
        type: string
      error:
        description: error
        type: string
      type:
        description: type
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: fotchin@mail.ru
    name: API Support
    url: https://vk.com/id250446192
  description: Comics store
  license:
    name: AS IS (NO WARRANTY)
  title: Comics Store
  version: "1.0"
paths:
  /comics/:
    get:
      description: Get a list of all comics
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ds.Comics'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ModelError'
      summary: Get all records
      tags:
      - Info
    post:
      description: Adding a new comics to database
      parameters:
      - description: Название
        in: body
        name: Name
        required: true
        schema:
          type: string
      - description: Рейтинг
        in: body
        name: Rate
        required: true
        schema:
          type: integer
      - description: Год производства
        in: body
        name: Year
        required: true
        schema:
          type: integer
      - description: Жанр
        in: body
        name: Genre
        required: true
        schema:
          type: string
      - description: Цена
        in: body
        name: Price
        required: true
        schema:
          type: integer
      - description: Количество серий
        in: body
        name: Episodes
        required: true
        schema:
          type: integer
      - description: Описание
        in: body
        name: Description
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ModelComicsCreated'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ModelError'
      summary: Add a new comics
      tags:
      - Add
  /comics/{uuid}:
    delete:
      description: Delete a comics via its uuid
      parameters:
      - description: UUID комикса
        in: query
        name: UUID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ModelComicsDeleted'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ModelError'
      summary: Delete a comics
      tags:
      - Change
    get:
      description: Get a comics via uuid
      parameters:
      - description: UUID комикса
        in: query
        name: UUID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ModelComicsDesc'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ModelError'
      summary: Get comics with corresponding name
      tags:
      - Info
    put:
      description: Change a description of comics via its uuid
      parameters:
      - description: UUID комикса
        in: query
        name: UUID
        required: true
        type: string
      - description: Новое описание
        in: query
        name: Description
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ModelDescChanged'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ModelError'
      summary: Change comics
      tags:
      - Change
schemes:
- http
- https
swagger: "2.0"
